# Generated by Django 3.2.5 on 2021-07-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210712_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbooks',
            name='content',
        ),
        migrations.AddField(
            model_name='addbooks',
            name='author',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='title',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
