# Generated by Django 3.2.5 on 2021-07-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210712_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='addbooks',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
