# Generated by Django 3.2.5 on 2021-07-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_addbooks_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='addbooks',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
