# Generated by Django 3.2.5 on 2021-07-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210712_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbooks',
            name='file',
        ),
        migrations.RemoveField(
            model_name='addbooks',
            name='time',
        ),
        migrations.AddField(
            model_name='addbooks',
            name='genre',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='addbooks',
            name='language',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
